<?php

return [
'Quienes' => 'Who we are',
'comiteJessica' => 'Register  & Basket Committee',
 'Jessica'=>'<p>I’d like you to know that as a Latina woman I’m filled with excitement, joy and pride to be 
              able to support this initiative and participate as a part of the planning committee at the 
              3rd symposium for Latino women, which seeks to maximize our potential and highlight the importance of women in the American society.</p>',
 'Jessica1'=>'<p> Dear Latino Women,
             My name is Jessica Cabrera, I am 51 years old, originally from Peru, happy mother of
             two wonderful daughters of 33 and 21 years old and a psychologist by profession. I immigrated to the United States about 11 years ago. Converted into a single mother and 
             with a little girl of the age of 10, I moved away from my beloved homeland, family, home, language, traditions and culture to come to this country filled with many dreams, illusions and seeking for new opportunities and challenges. </p>
            <p> Some of the biggest challenges I had to face were undoubtedly the language barrier along with the beginning of a new life in a foreign country while raising a little girl. I fortunately had the opportunity to learn the language a few years ago, and with great perseverance I’m still facing new challenges which inspire me to keep working hard to achieve my personal and professional goals.</p>
            <p>While maintaining a full-time job and continuing my studies in college, I always considered it important to learn about how the educational system works so that my daughter could quickly adapt to her school and that is how I gradually became involved as a volunteer and started participating as a facilitator and serving as a guide for many Latino parent groups, which contributed to the formation of what today is known as “Natural Leaders”  and was able to become one of the first natural leaders at the Edmonds School District. </p>
            <p>I currently belong to the “EAACH” committee which means equal partnership for success, I was also able to complete the Parent Mentor certification program at the Edmonds Community College, and I got certified as a Parent Educator in Positive Discipline. I currently work for the group FLY (Foreign Language for Youth) as a Spanish teacher for several elementary schools in different districts. </p>
           <p> This life is a constant learning experience and I believe that every single one of us can achieve our goals and dreams as long as we support and fight together as the strong women that we are, and truly hope that our stories can serve as an inspiration for many women seeking means of support for the benefit of their personal and professional development. We look forward to see you all there!</p>', 
  'comiteTania' => 'Finance Committee',  
  'Tania' => '<p>My goal as an organizer of the North Seattle College Latina Symposium is to create unity within the Latinas.  Everyone              has their own dreams in life.
           I am a true believer that Latinas Women can be successful at any goal they set their mind to with the right support.</p>',
 'Tania1'=> '<p>My dream has come through with hard work, support and encouragement from many people around me that                                   includes family members, friends, and good teachers who  believed in me.</p> 
            <p>Now I am a Licensed Social Worker with a Masters from the University of Washington and also an Adlerian therapist, Parenting coach and a Parent Education Instructor at North Seattle College.  As a mother of three kids, my dream is that as our kids grow up and navigate the world, there will be lot more Latina Women in power and as role models.</p>  
            <p>We need more Latinas to empower our children and show them that they all can reach their dreams.</p>
            <p>This Latina Symposium, a dream that was only made possible by the grant provided by the Parent Education Program from North Seattle College.  The dream is to organize and bring together Latinas from different educational backgrounds, economical status, and cultures to form a sense of community and to empower each other and make their dreams a possibility.</p>
            <p>This is my story:</p>
            <p>My family relocated from Mexico to the United States looking for a better future about 20 years ago. When I was 15 years old and could barely speak or understand English, my high school carrier counselor in San Antonio asked me in broken Spanish, “What do you want to do when you grow up?”  I answered without a hesitation, “A nurse!”.  Growing up in Mexico and watching my Godmother who was a town nurse, I was inspired to become a nurse. So, with a high confidence & enthusiasm, I answered “A Nurse!”.</p>
            <p>The counselor looked at me with a puzzled look on her face.  She then proceeded to give me a carrier/vocational test which I did my best with my limited English knowledge.</p> 
            <p>The counselor graded my test and came back with a striking news that I will be no more than a fast food restaurant worker.  My heart sank but my hopes endured.  From that point on I made a conscious decision that I will not only become successful but also be a bridge to encourage and motivate any minority or less privileged population;especially Latinas to continue their own dreams.</p>',
 'Velia' => '<p>Mi interés de participar en el Comité Organizador para el 3er Simposio de la Mujer Latina es: que por              medio de esta oportunidad pueda apoyar y facilitar los recursos necesarios para empoderar a otras mujeres.               Ya que yo creo firmemente en el papel tan importante que juega la mujer en la familia y en la sociedad. Y                nosotras como mujeres inmigrantes en este país que pasamos por diferentes cambios y etapas necesitamos de                ese apoyo que nos ayude a salir adelante.</p>',
 'Velia1'=> '<p>En mi experiencia al llegar a vivir a este país fué una gran oportunidad de cambio, que también trajo                 consigo muchas situaciones en las cuales he buscado reinventarme día a día para poder lograr mis objetivos               y no desfallecer en el intento y luchar por lo quiero.</p>
             <p>Ya que yo soy de las mujeres que creen que no hay motivos para abandonar nuestros sueños y que es posible poder alcanzar lo que queremos y llevar también al mismo tiempo una vida equilibrada con los diferentes roles que nos tocan vivir.</p>
             <p>Soy originaria de Puebla, México. Estoy casada y soy madre de dos hermosos niños. Tengo casi 11 años viviendo aquí en el estado de WA. Estudie Licenciatura en Turismo en mi país natal. Siempre he tenido el deseo de superarme continuamente y de aprender cosas nuevas cada día; ya que el saber te da poder. Por lo cual desde que llegue a este país ha sido un continuo aprendizaje y preparación ya que quiero ser un modelo positivo y ejemplo vivo para mis hijos y enseñarles que si se puede a pesar de las barreras y obstáculos que te presente la vida.</p>
             <p>Actualmente trabajo en el Centro Familiar de Shoreline y de Northshore en la ciudad de Bothell como facilitadora del programa Aprender Jugando, el cual me ha dado la oportunidad de trabajar con familias de diferentes culturas. También obtuve una certificación como Educador de Padres en Disciplina Positiva y es algo que me encanta hacer compartir con otros padres nuevas técnicas para la crianza de nuestros hijos, que son nuestro gran futuro.</p>',           
   'Perla' => '<p>Retomar ese suspiro de esperanza y compartirlo con las demás mujeres que buscan crecer en este país es             lo que me sigue motivando a ser parte de este simposio. Como mujer, creo que tenemos el compromiso de                  formar  a nuestras familias con amor, respeto y   educación. Es importante reconocer nuestro roll,                     educarnos para así  poder motivar a  nuestras familias de que tenemos que evolucionar, enseñarles a soñar,             a crear metas y  sobre  todo apoyar a quien va a nuestro lado.</p>',
   'Perla1' => '<p>Es importante reconocer nuestro roll, educarnos para así poder poder motivar a nuestras familias de               que tenemos que evolucionar, enseñarles a soñar, a crear metas y sobre todo apoyar a quién va a nuestro                lado.</p>  
              <p>Cuando uno migra sin importar bajo que circunstancia todos probamos ese sabor a vacío, ese sentir de dejar lo que se era, y aun en contra de nuestros ideales o perspectivas la señora vida nos va moldeando. Crecemos consciente o inconscientemente, y ese cambio, esa evolución siempre será un regalo. </p>
              <p>Soy Perla, hija, madre, esposa y migrante. Viajo con la vida, y a veces me pierdo en ella. Llegue al estado de Washington con dos maletas, las cuales las tuve que dejar y con ello algunas de mis limitaciones y miedos. Seguí mis sueños  y migre a Dublín.
              Después de experimentar ser madre y estudiante termine mi maestría y la vida me regreso a Seattle. Hoy estoy aquí, ayudando en este evento para crecer junto con todas las mujeres que llegan al simposio con miedos,  anhelos y sueños.  </p>',
                 
   'Sixta' => '<p>Amo la gente y las historias detrás de sus caras, creo que las sonrisas, la buena energía y la bondad                pueden hacer la diferencia en nuestras vidas. Llegué al simposio como invitada el primer año del evento                 cuando recién llegaba de la Republica Dominicana y disfruté tanto la experiencia que decidí  unirme al                  comité organizador desde hace ya dos años. </p>',
   'Sixta1'=> '<p>Compartir con tantas mujeres luchadoras, inspiradoras, ha sido una experiencia que me llena de esperanza             en cuanto a el futuro de las Latinas en los EU. </p>
              <p>Vivo en Seattle junto a mi esposo e hijo, disfruto de las flores, la buena lectura y escribo periódicamente en mi blog Gente, Historias y Sonrisas.</p>', 
    'Elia' => '<p> I like work as volunteer with agencies that help the Hispanic community either here or in Jalisco                 state.  I also like to take pictures, yoga, read, music,going to walk  or have coffe with a good 
              friend.</p>',      
   'Elia1' => '<p>My name is Elia Gómez. I was born in Guadalajara, Jalisco México. I started the adventure as immigrant              19 years ago when my husband got an offer job.
              We have three children, two of them at college and the youngest at 5th grade.
              I know that the woman has an important roll in the family and I consider myself lucky to have the opportunity to help and support them. </p> ',
 'Guillermo' =>'<p>I’ve also come to believe that women are the key to creating a more just and content world. They have                 the capacity and lived experience to appreciate and understand what human beings need for a decent life.                  The more successes women accumulate, the more secured and healthy their family.  And for me, the children                 of these women have a greater chance to do well in school and take hold of their own dreams.  So it’s in my               interest to see a growing number of Latina women succeeding.</p>',
  'Guillermo1'=>'<p>The success of our students is directly tied to the success of their mothers.  The women that have                  participated in the Symposium appreciate the power of hopes and aspirations.  And all of men, women and us               that can help provide tools and resources for their success should do so. </p>
                <p> I was born in Costa Rica and raised in the Big Apple. I am a family support worker for Seattle Public Schools.  I have a Master’s degree in human development.  I have spent the last 15 years in the social service sector and a dedicated human rights supporter.  I have also volunteered in behalf of Latino arts and culture, and been privileged to work with many ethnic and minority communities.</p>
                <p> For the last few years I have worked in a school with a large Latino population.  This experience has given me a deeper appreciation of the challenges facing the families I work with, especially the mothers.</p>
                <p>I’ve been inspired by my mom and the neighborhood we grew up in.  Historically women have stood behind their men, supporting them in many ways while their husbands staked out a place in the world for themselves. The world economy has forced the family to make the mother work more taking several jobs besides her responsibility at home, because now moms don’t have much of a choice but to go out into the world and compete for jobs. Instead of one partner standing behind the other, why not join the two and hand in hand. This is a healthier, enriching and powerful way to make the women’s dreams, and that of the entire family, come true.</p>
                <p>My mom came to this country in her early thirties, and spent most her working days cleaning houses or doing factory work.  She had a good heart and mind, but we lived in a very poor and dangerous part of New York City.  It was very hard for her to find and secure contacts or resources to realize her own dreams.  The moms I currently work with all carry a little bit of my own mom, similar aspirations and struggles, moments of sadness and melancholy; moments of laughter and hope.  I hear them, I hear her.</p>
                <p>My mom and my job have helped me to appreciate the power of dreams and aspirations.  People must allow themselves to hold on to and nourish their hopes and passions.  Sometimes that is the only thing that keeps them strong in the face of trauma and struggle.</p>
                <p>I try to remember this when I come to work every day.  Most of the people I interact with at work are women, and I try to do one of two things or both, if I can, not to stand in the way of their dreams, and if they seem ready to “fly” find ways to give them more tools for a successful flight.   A great part of my job now is about nourishing dreams.</p>'
];