<?php

return [
'Quienes' => 'Who we are',
 'nomTania' => 'Tania Hino',
 'comiteTania' => 'Finance & Presenter Committee',  
  'Tania' => '<p>My goal as an organizer of the North Seattle College Latina Symposium is to create unity within the Latinas.                                      Everyone  has their own dreams in life.
              I am a true believer that Latinas Women can be successful at any goal they set their mind to with the right support.</p>
            <p>My dream has come through with hard work, support and encouragement from many people around me that  includes family members, friends, and good teachers who  believed in me.</p> 
            <p>Now I am a Licensed Social Worker with a Masters from the University of Washington and also an Adlerian therapist, Parenting coach and a Parent Education Instructor at North Seattle College.  As a mother of three kids, my dream is that as our kids grow up and navigate the world, there will be lot more Latina Women in power and as role models.</p>  
            <p>We need more Latinas to empower our children and show them that they all can reach their dreams.</p>
            <p>This Latina Symposium, a dream that was only made possible by the grant provided by the Parent Education Program from North Seattle College.  The dream is to organize and bring together Latinas from different educational backgrounds, economical status, and cultures to form a sense of community and to empower each other and make their dreams a possibility.</p>
            <p>This is my story:</p>
            <p>My family relocated from Mexico to the United States looking for a better future about 20 years ago. When I was 15 years old and could barely speak or understand English, my high school carrier counselor in San Antonio asked me in broken Spanish, “What do you want to do when you grow up?”  I answered without a hesitation, “A nurse!”.  Growing up in Mexico and watching my Godmother who was a town nurse, I was inspired to become a nurse. So, with a high confidence & enthusiasm, I answered “A Nurse!”.</p>
            <p>The counselor looked at me with a puzzled look on her face.  She then proceeded to give me a carrier/vocational test which I did my best with my limited English knowledge.</p> 
            <p>The counselor graded my test and came back with a striking news that I will be no more than a fast food restaurant worker.  My heart sank but my hopes endured.  From that point on I made a conscious decision that I will not only become successful but also be a bridge to encourage and motivate any minority or less privileged population;especially Latinas to continue their own dreams.</p>',
'nomJessica' => 'Jessica Cabrera',
'comiteJessica' => 'Register - Basket Committee',
 'Jessica'=>'<p>I’d like you to know that as a Latina woman I am filled with excitement, joy and pride to be 
              able to support this initiative and participate as a part of the planning committee at the 
              3rd symposium for Latino women, which seeks to maximize our potential and highlight the importance of women in the American society.</p>
             <p> Dear Latino Women,
             My name is Jessica Cabrera, I am 51 years old, originally from Peru, happy mother of
             two wonderful daughters of 33 and 21 years old and a psychologist by profession. I immigrated to the United States about 11 years ago. Converted into a single mother and 
             with a little girl of the age of 10, I moved away from my beloved homeland, family, home, language, traditions and culture to come to this country filled with many dreams, illusions and seeking for new opportunities and challenges. </p>
            <p> Some of the biggest challenges I had to face were undoubtedly the language barrier along with the beginning of a new life in a foreign country while raising a little girl. I fortunately had the opportunity to learn the language a few years ago, and with great perseverance I’m still facing new challenges which inspire me to keep working hard to achieve my personal and professional goals.</p>
            <p>While maintaining a full-time job and continuing my studies in college, I always considered it important to learn about how the educational system works so that my daughter could quickly adapt to her school and that is how I gradually became involved as a volunteer and started participating as a facilitator and serving as a guide for many Latino parent groups, which contributed to the formation of what today is known as “Natural Leaders”  and was able to become one of the first natural leaders at the Edmonds School District. </p>
            <p>I currently belong to the “EAACH” committee which means equal partnership for success, I was also able to complete the Parent Mentor certification program at the Edmonds Community College, and I got certified as a Parent Educator in Positive Discipline. I currently work for the group FLY (Foreign Language for Youth) as a Spanish teacher for several elementary schools in different districts. </p>
           <p> This life is a constant learning experience and I believe that every single one of us can achieve our goals and dreams as long as we support and fight together as the strong women that we are, and truly hope that our stories can serve as an inspiration for many women seeking means of support for the benefit of their personal and professional development. We look forward to see you all there!</p>',
   'leerMas' => 'Read more',
'leerMenos' => 'Read less',
'nomVelia' => 'Velia Lara',
'comiteVelia' => 'Banquet -  Decoration Committee',
 'Velia' => '<p>I was interested in participating in the Latinas Symposium board because through this opportunity I can support and facilitate some resources to empower other women.  I firmly believe in the important role that women play in family and society, and us, as women and immigrants who come to this country and go through so much changes, we need this type of support to help us move forward.</p>
 <p>In my experience, coming to live here was a great opportunity for change; it also faced me with it situations where I had to re invent my self day by day, to be able to achieve my goals and not give up trying, and also fight for what I want; I am the type of women who believes there’s no reason to give up our dreams and that is possible to achieve whatever we want, and also have a balanced life with all the roles we have to embrace.</p>
             <p>I am originally from Puebla, Mexico. I am married and I am the mother of two beautiful children. I have 11 years living in the state of Washington and I have a bachelor’s degree in Tourism. I’ve always had the desire to succeed and learn new things everyday, I believe knowing is power, and since I came here I don’t stop learning because I want to be a role model to my kids and teach them that things can get done beside the barriers we encounter in life.</p>
             <p>Currently I work in Centro familiar Shoreline and Northshore, in Bothell as a facilitator of the program “ To learn playing” where I have the opportunity to work with families from different cultures. I also have a certification as educator for parents in positive discipline and that’s something that I love: to share with others the techniques of upbringing our kids, who are the future.</p>', 
'nomXimena' => 'Ximena Grollmus',            
'comiteXimena' => 'Banquet Committee',
 'Ximena' => '<p>I am happy to  be part of the planning committee at Latina Symposium.
              I am from Concepción, Chile, but I moved to Seattle on 1997. In Chile, I worked as a teacher from 7 years    
              I went to graduate school at the University of Washington in the School Psychology department and became a School Counselor.</p>
             <p>After graduating I spent some time raising my 2 beautiful children.  I dedicated time to study more about                                        Adlerian  psychology and Positive Discipline.  When I started working again, I was providing counseling services to                                  children and their  families in a local counseling agency.</p>
              <pI worked as a therapist doing FPS (Family Preservation Services) with families that have been reported to CPS.  I became a certified PD trainer on 2012 by the PDA.  I had worked with groups of parents from different cultures, in different countries, from different school districts in WA state and with teachers and school personnel from the big Seattle area.</p>
              <p>The work with parents it is one of my passions.  The positive changes that families experience when they start using PD give me a lot of satisfaction and love for the work we all do in this area. Currently, I am working as a school counselor at an elementary school in Shoreline and enjoying a lot the work with the students.</p>',            
'nomPerla' => 'Perla Mendoza',          
'comitePerla' => 'Publicity-Website Committee ',
   'Perla' => '<p>Retake that sigh of hope and share it with other women looking to grow in this country, it is what keep to motivate me to be part              of this symposium.</p>
               <p>As woman, I believe that we have the commitment to form our families with love, respect and formal education. It is very important to know our roll, to educate ourselves, so that, we can establish goals and most of all, support the ones who go by our sides.</p>
              <p>When we migrate, no matter under what circumstances, we all taste that emptiness, that feeling of not being what we used to be, and even against our ideals and perspectives,  lady life keeps molding us.</p>  
              <p>We grow consciously or unconsciously, and that change, that evolution will always be a gift.</p>
              <p>I am Perla, daughter, mother, wife,  and migrant. I travel with life, and sometimes I get lost in it.  I came  to Washington State with two suitcases, the ones I had to leave behind and with them some limitations 
              and fears. I followed my dreams and migrate to Dublin.</p>
              <p>After experience being mother and student, I finished my master in Applied Digital Media  and life took me back to Seattle. Now I am here, helping in this event, to grow with all the women that come to the symposium with fears, hopes and dreams.</p>',
'nomSixta' => 'Sixta Morel',   
'comiteSixta' => 'Publicity Committee ',
   'Sixta' => '<p>When I moved to Seattle from the Dominican Republic I left behind everything I knew:  my hometown, my family, my friends and my career. I married the love of my life and decided to leave it all and start over in this beautiful city of Seattle. Far away from the lovely Dominican weather and my circle, and knowing that I would probably had to wait a good time before ‘standing on my feet ‘ again I made a decision: It was my choice to come, so I would make the best of it, and since the beginning the journey has been nothing but rewarding.</p>
              <p>I started working in the television business since the age of 17, I am experienced as news anchor, magazines host, arts and entertainment editor, bilingual MC, interviewer, and also as producer in my own inspirational TV show: "Vida y Valores".  Graduated as Radio and TV broadcaster, I hold a bachelor  degree in Business Administration and certificates in Cultural Journalism and Public Relations and Strategic Communications. </p>',
'nomAmarilis' => 'Amarilis Aranguren',
'comiteAmarilis' => 'Content - Register Committee', 
'Amarilis' => '<p>I’m against injustice and women are affected by this every day. I met Tania Hino and Perla Mendoza in the Seattle Public Library,   in the Spanish Storytime for kids. They are the heart of the Latina Symposium and an example of the strength that every Latina has                    inside.</p>
              <p>We need more women with awareness and leadership to lead the Latin-American community. In our countries, we know that every family has a mighty member that push them to be better, the women who is responsible for the family and now is an active component of the changes in the community.</p>
              <p>I wanna help to empower the Latinas, so they can lead their families and communities in a superior way. I love to be part of this program to help the Latinas. When you help women to realise they abilities to change their life, you open a new dimension in her life and the people around.</p>
              <p>I am a Venezuelan journalist, Internet enthusiast, and early adopter, living in Seattle, WA, in the USA. Social Medial, digital content, and planning are my specialties. I have more than 10 years of experience working with news writing for TV and Internet. The last 6 years, I’ve been working with digital content optimized for SEO, Social Media strategy and content planner. </p>', 
'nomAngie' => 'Angie Esquivel',  
 'comiteAngie' => 'Volunteer Committee',
       'Angie' => '<p>The border was part of my life since I was a little girl. I grew up in the north of Mexico, in the border with the US, in a            bicultural community divided by a river. Crossing to the “other side”, was our daily bread. The American culture and English language          were part of my upbringing. Speaking English helped me when I traveled to other countries and to interact with people of other                 cultures.</p>
             <p>As destiny would have it, I moved to Germany to study. There, in a totally different country than mine, with an unknown language, I    had to reinvent myself to be able to adapt to my new reality. It wasn’t easy, and in the beginning mainly because of the language       barrier, I felt handicapped, ignorant and most of all out of place. I had to learn the customs, traditions and ideology of my new home.  This process made me understand better, all the people that like me leave their countries behind, to fulfill a dream or to pursue a      better life.</p>
             <p>I am an administrator by profession but my life’s work has been that of an educator. I have studied in various universities in three different countries. That has helped me have a wider vision of diverse educational systems. I like technology and I have always integrated it to my classes and other activities I do. I believe that education is the best way for personal development. I’m very interested in helping others to achieve their dreams and have a better life.</p>
             <p>I have been living in Seattle for four years. My family are my husband and two kids. Now as a full-time mother, I have had to reinvent myself one more time. I face the challenge and excitement of raising my kids in a multilingual and multicultural home. At the same time, as I am not formally working, I have looked for other activities where I can I feel productive and make a contribution to the community.</p>
             <p>I am a consultant to the Latin America division of the family business. I work as a volunteer in the Public Library and serve as secretary of the board of a Spanish co-op preschool. Furthermore, I feel very lucky to be part of “Simposio de Mujeres Latinas”.</p>',
'nomVeronica' => 'Veronica Duran', 
'comiteVeronica' => 'Souvenir Committee',
 'Veronica' => '<p>17 years ago I came from Ecuador, where I had studied International Business and where I had 
            completed a Masters in Marketing.  One year after arriving in Portland, Oregon, I was presented
            the opportunity to work at Oregon Health and Sciences University as a Spanish Interpreter.</p>
            <p>This job allowed me to meet many people from different origins and cultures.  Through this
            experience I learned that while Spanish speakers were often looking for help with English they were also looking for a chance to share part of their life with others with whom they had things in common.</p>
            <p>Now that I am dedicated to raising my three children here in Seattle, I realize that I also want to share my experiences with other women so that we can mutually enrich ourselves and thrive together.</p>', 
 'nomleonor' => 'Leonor',   
'comiteLeonor' => 'Exhibitor Tables Committee',
   'Leonor' => '<p>I was born in Turbo a coastal municipality of Antioquia department in Colombia. I grew up in a family of 3 sisters and a brother.              My mother, a house wife and my father a peddler of sweets and lottery tickets. These two wonderful human beings, specially my mom,                 instilled me to become a teacher. Because it was the most promising profession at that time. My mother did not have to work so hard,               because since I was a kid, I played to be a teacher. I liked it a lot, and it became my goal.</p>
               <p>In 1996, I finished my degree in Education and a year after my graduation, I was already working in the State of 
               Antioquia. I worked 18 years in public schools in my municipality. While working, I studied Educational management, in that moment, my professional life totally changed. I had the privilege of sharing with teachers that transformed the way I saw education. I wanted to change the educative system that I was working with, a system where it was allowed to degrade students.</p> 
               <p>This factors and some family issues, brought me to United States with my three kids and very aware that I had
               to start from scratch. In this way, I experienced what many men and women have to live in a new country, that solitude and vulnerability. The most sorrow I felt and I keep feeling, is how our own Latino community want to cut your wings (stop your dreams) Despite of that, I have always kept in my mind the conviction of not letting anybody break my spirit. For that reason, I kept looking for opportunities. I enrolled to a course of children education. There I met the person who connected me with the two schools I am working currently. The two schools I call blessings, because they have given me the opportunity to keep learning, growing and meeting wonderful people.</p> 
               <p>Last year, I saw one of the TV programs advertising the symposium, and I knew I wanted to be part of it. Unfortunately when I called, the registration was already closed. Luckily, as the world is so small, today I am very happy to be part of the organization team of this wonderful event. I have the conviction that I can contribute a bit and tell Latina women do not let anyone break your spirit. We can do it!!</p>',  
  'Aliados' => 'Our  Allies',
  'nomGuillermo' => 'Guillermo Carvajal',      
 'comiteGuillermo' => 'Finance Committee',
 'Guillermo' =>'<p>I’ve also come to believe that women are the key to creating a more just and content world. They have   the capacity and lived experience to appreciate and understand what human beings need for a decent life.   The more   successes women accumulate, the more secured and healthy their family.  And for me, the children    of these women     have a greater chance to do well in school and take hold of their own dreams.  So it’s in my   interest to see a  growing number of Latina women succeeding.</p>
             <p>The success of our students is directly tied to the success of their mothers.  The women that have                            participated in the Symposium appreciate the power of hopes and aspirations.  And all of men, women and us                        that can help provide tools and resources for their success should do so. </p>
                <p> I was born in Costa Rica and raised in the Big Apple. I am a family support worker for Seattle Public Schools.  I have a Master’s degree in human development.  I have spent the last 15 years in the social service sector and a dedicated human rights supporter.  I have also volunteered in behalf of Latino arts and culture, and been privileged to work with many ethnic and minority communities.</p>
                <p> For the last few years I have worked in a school with a large Latino population.  This experience has given me a deeper appreciation of the challenges facing the families I work with, especially the mothers.</p>
                <p>I’ve been inspired by my mom and the neighborhood we grew up in.  Historically women have stood behind their men, supporting them in many ways while their husbands staked out a place in the world for themselves. The world economy has forced the family to make the mother work more taking several jobs besides her responsibility at home, because now moms don’t have much of a choice but to go out into the world and compete for jobs. Instead of one partner standing behind the other, why not join the two and hand in hand. This is a healthier, enriching and powerful way to make the women’s dreams, and that of the entire family, come true.</p>
                <p>My mom came to this country in her early thirties, and spent most her working days cleaning houses or doing factory work.  She had a good heart and mind, but we lived in a very poor and dangerous part of New York City.  It was very hard for her to find and secure contacts or resources to realize her own dreams.  The moms I currently work with all carry a little bit of my own mom, similar aspirations and struggles, moments of sadness and melancholy; moments of laughter and hope.  I hear them, I hear her.</p>
                <p>My mom and my job have helped me to appreciate the power of dreams and aspirations.  People must allow themselves to hold on to and nourish their hopes and passions.  Sometimes that is the only thing that keeps them strong in the face of trauma and struggle.</p>
                <p>I try to remember this when I come to work every day.  Most of the people I interact with at work are women, and I try to do one of two things or both, if I can, not to stand in the way of their dreams, and if they seem ready to “fly” find ways to give them more tools for a successful flight.   A great part of my job now is about nourishing dreams.</p>'
];