<?php

return [
'Jessica'=> '<p>Quiero que sepan que como mujer Latina me llena de emoción, alegría y orgullo apoyar esta iniciativa y                   participar como parte del comité de planificación en el segundo simposio de mujeres latinas, el cual                       busca maximizar su potencial y resaltar la importancia de la mujer latina en la sociedad   
              estadounidense.</p>', 
'Jessica1' =>'',   
  'Tania' => '</p>My goal as an organizer of the NSC Latina Symposium is to create unity within the Latinas.  Everyone has            their own dreams in life.  I am a true believer that Latinas can be successful at any goal they set their                mind to with the right support.</p>',
   'Tania1'=> '<p>My dream has come through with hard work, support and encouragement from many people around me that                  includes family members, friends, and good teachers who  believed in me.</p> 
               <p>Now I am a Licensed Social Worker with a Masters from the University of Washington and also an Adlerian therapist, Parenting coach and a Parent Education Instructor at North Seattle College.  As a mother of three kids, my dream is that as our kids grow up and navigate the world, there will be lot more Latina Women in power and as role models.</p>  
               <p>We need more Latinas to empower our children and show them that they all can reach their dreams.</p>
               <p>This Latina Symposium, a dream that was only made possible by the grant provided by the Parent Education Program from North Seattle College.  The dream is to organize and bring together Latinas from different educational backgrounds, economical status, and cultures to form a sense of community and to empower each other and make their dreams a possibility.</p>
               <p>This is my story:</p>
               <p>My family relocated from Mexico to the United States looking for a better future about 20 years ago. When I was 15 years old and could barely speak or understand English, my high school carrier counselor in San Antonio asked me in broken Spanish, “What do you want to do when you grow up?”  I answered without a hesitation, “A nurse!”.  Growing up in Mexico and watching my Godmother who was a town nurse, I was inspired to become a nurse. So, with a high confidence & enthusiasm, I answered “A Nurse!”.</p>
               <p>The counselor looked at me with a puzzled look on her face.  She then proceeded to give me a carrier/vocational test which I did my best with my limited English knowledge.</p> 
               <p>The counselor graded my test and came back with a striking news that I will be no more than a fast food restaurant worker.  My heart sank but my hopes endured.  From that point on I made a conscious decision that I will not only become successful but also be a bridge to encourage and motivate any minority or less privileged population;especially Latinas to continue their own dreams.</p>',
   'Sixta' => '<p>“Llegué al simposio como invitada el primer año del evento cuando recién llegaba de mi país, disfruté               tanto la experiencia que decidí  unirme al comité organizador desde hace ya dos años. Compartir con tantas              mujeres luchadoras, inspiradoras, ha sido una experiencia que me llena de esperanza en cuanto a el futuro de            las Latinas en los EU. Feliz de colaborar con tan hermosa iniciativa". </p>',    
 'Sixta1'=> '<p>“Amo la gente y las historias detrás de sus caras, creo que las sonrisas, la buena energía y la bondad                 pueden hacer la diferencia en nuestras vidas” . Profesional de la comunicación bilingüe quien se inició en                los medios de comunicación en su natal Republica Dominicana  a los 17 años.  Su experiencia incluye la                    conducción y producción de televisión, conducción de noticias, entrevistas, Editora de Artes y Espectáculos,              maestrías de ceremonias, comerciales, voice overs y actuación. Graduada de Administración de Empresas y                   Locución, cuenta con diplomado en Periodismo Cultural, así como en Comunicación Estratégica y Relaciones                  Públicas de la Universidad de Washington. Periódicamente escribe en su blog "Gente, Historias y Sonrisas”.              </p>',          
    'Elia' => '<p> like work as volunteer with agencies that help the Hispanic community either here or in Jalisco state.             I also like to take pictures, yoga, read, music,going to walk  or have coffe with a good friend.</p>',
   'Elia1' => '<p>My name is Elia Gómez. I was born in Guadalajara, Jalisco México. I started the adventure as immigrant              19 years ago when my husband got an offer job.
              We have three children, two of them at college and the youngest at 5th grade.
              I know that the woman has an important roll in the family and I consider myself lucky to have the opportunity to help and support them. </p> ',
 'Guillermo' =>'<p>I’ve also come to believe that women are the key to creating a more just and content world. They have                 the capacity and lived experience to appreciate and understand what human beings need for a decent life.                  The more successes women accumulate, the more secured and healthy their family.  And for me, the children                 of these women have a greater chance to do well in school and take hold of their own dreams.  So it’s in my               interest to see a growing number of Latina women succeeding.</p>'
];