<?php

return [
'newsMaru' => ' <h1>Maru Mora Villalpando awarded the El Puño de Oro, “Fist of Gold.”</h1>
            <h2>The Third Latin Women’s Symposium unanimously agreed to award El Puño de Oro to the political activist Maru Mora Villalpando.  Her work as the founder of Latino Advocacy to defend the human rights of the Latin community and the racial struggles of this minority, make her worthy of this recognition which is given to women who are an example in their community.</h2>
            <h3>Amarilis Aranguren Sánchez <span class="grey"> / </span> April 11, 2016</h3>',
  'grafico' => 'Photo from Internet',
'newsMaru1' => ' <p><span class="CapitalLetter">M</span>aru Mora Villalpando arrived to The United States in 1992 from México, afraid of the violence in her country caused by the political instability.  Her experience as an undocumented immigrant for 20 years, led her to dedicate her life to help others who live similar circumstances that she has encountered.</p>
        <p>Her mission is to help Latinos who are struggling with Immigration cases and help them become educated on how to navigate the Immigration system in the United States.  Latino Advocacy, the organization founded by Mora Villalpando also helps to organize the Latino community through consulting and focus groups both in civil justice and immigrant rights in the state of Washington. 
        Maru Mora Villalpando didn’t need a College degree to lead the Latino immigrant community against deportations, nor to organize protests in front of the Northwest Center of Deportation in Tacoma, Washington.  Her role as a leader and organizer of the community is inspired on her own experience as an undocumented immigrant in the United States.</p> 
        <p>Fifteen years ago, after the birth of her daughter Josefina Mora, she began to inform herself about the immigration rights and actively committing to the racism and intolerance that many immigrants face.  “I wanted to learn about my rights, connect with other members of the undocumented community and begin to create a coalition that demanded to be treated as human beings,” she explained in an article published in 2015.</p>
        <p>Her role as a fighter and advocate of Human Rights of Latin immigrants in the United States is recognized in all the American Continent.  “Not one more deportation” is an example of what the Latin women can do when they know their rights and feel confident.</p>  
        <p>El Puño de Oro, “fist of gold” is the highest recognition that the Latin Women’s Symposium awards to the activist that fight to empower the community and who are an example of leadership for women.  The obstacles that Maru Mora Villalpando has faced in her life have not been a reason to give up but on the contrary, they motivate her to reach her goals with more determination.
        Join us next Saturday May 21st to award her with this recognition.</p> ',
'leerMas' => 'Read more',
'leerMenos' => 'Read less',
'grafico1' => 'Genesis Photography',
'newsReinventandonos' => '<h1>"Reinventing after migrating”</br>
       is the theme of the Third Latina Symposium</h1>
      <h2>All families who have migrated to the United States had to go through the situation of adapting their lives to different customs. Considering that the issue of immigration is so linked to the Latino community in Seattle, Washington, the Third Latina  Symposium will be dedicated this year to address this reality.</h2>
      <h3>Amarilis Aranguren Sánchez <span class="grey"> / </span> April 04, 2016</h3>',
'newsReinventandonos1' => ' <p>“<span class="CapitalLetter">R</span>einventing after migrating" is the theme around which panelists and speakers will talk about to the 225 event participants, though their lives, they will prove that it is 
possible to get out of this transition successfully. The process of adapting to a new culture, a new environment, without forgetting the traditions that everyone brings from their country and their families, is the challenge of the Latino community every day.</p>
        <p>According to a report of the United Nations, there are 26 million of Latin American immigrants in the United States. A large group of people whom daily struggle against racism and discrimination, striving for a better life.
        The process of settling in another country either by legal or illegal ways,  generates traumatic situations in the families involved in the physical distance from loved ones. Latina women have an important role in the process of adapting their families to a new lifestyle.</p>
        <p>This May 21, 2016, the human rights activist of Latinos Maru Mora Villalpando will talk about her experience in the defense of the community, its role as a founder of Latino Advocacy and will also show how the leadership of women can transform realities.</p>
       <p>Maru Mora Villalpando will receive the award "Golden Fist" given by the Latina Symposium committee, and will be the keynote speaker of the event.</p>
       <p>Also as participating as a speaker, Maria-Jose "Cote" Soerens, executive director of Bridges, an organization that mobilizes resources to psychologically help undocumented Latinos in the state of Washington, and also Lizbeth Gutierrez, Ph.D. candidate in Washington State University and a specialist in studies of women.</p>
       <p>The social worker Elodia Gonzalez will show by example how the hard work pays off and can change the lives of all those who migrate. Gonzalez helps the Latino community from Seamar and other practices to improve anxiety problems. Her story will show the capacity of transformation that women have, she did it her self, when after having children, she decided to reinvent her career to become an invaluable contribution to the community.</p>
       <p>The Third Latina Symposium wants to encourage all women who migrated to this country, and inspire them to achieve more every day, because life doesn’t ends when arriving in to the United States. That is just the beginning of something better. "Reinventing after migrating" is a sample of what the Latinas are capable of doing with their tenacity.</p>
       <p>The invitation is to participate in the Third Latina Symposium, to be held in North Seattle College, on Saturday 21 May 2016. 225 women will have the opportunity to participate in this free event that will take place from 10:00 am until 3:30 pm.</p>'
 
];