<?php

return [
'newsMaru' => ' <h1>Maru Mora Villalpando awarded the El Puño de Oro, “Fist of Gold.”</h1>
            <h2>The Third Latin Women’s Symposium unanimously agreed to award El Puño de Oro to the political activist Maru Mora Villalpando.  Her work as the founder of Latino Advocacy to defend the human rights of the Latin community and the racial struggles of this minority, make her worthy of this recognition which is given to women who are an example in their community.</h2>
            <h3>Amarilis Aranguren Sánchez <span class="grey"> / </span> April 11, 2016</h3>',
  'grafico' => 'Photo from Internet',
'newsMaru1' => ' <p><span class="CapitalLetter">M</span>aru Mora Villalpando arrived to The United States in 1992 from México, afraid of the violence in her country caused by the political instability.  Her experience as an undocumented immigrant for 20 years, led her to dedicate her life to help others who live similar circumstances that she has encountered.</p>
        <p>Her mission is to help Latinos who are struggling with Immigration cases and help them become educated on how to navigate the Immigration system in the United States.  Latino Advocacy, the organization founded by Mora Villalpando also helps to organize the Latino community through consulting and focus groups both in civil justice and immigrant rights in the state of Washington. 
        Maru Mora Villalpando didn’t need a College degree to lead the Latino immigrant community against deportations, nor to organize protests in front of the Northwest Center of Deportation in Tacoma, Washington.  Her role as a leader and organizer of the community is inspired on her own experience as an undocumented immigrant in the United States.</p> 
        <p>Fifteen years ago, after the birth of her daughter Josefina Mora, she began to inform herself about the immigration rights and actively committing to the racism and intolerance that many immigrants face.  “I wanted to learn about my rights, connect with other members of the undocumented community and begin to create a coalition that demanded to be treated as human beings,” she explained in an article published in 2015.</p>
        <p>Her role as a fighter and advocate of Human Rights of Latin immigrants in the United States is recognized in all the American Continent.  “Not one more deportation” is an example of what the Latin women can do when they know their rights and feel confident.</p>  
        <p>El Puño de Oro, “fist of gold” is the highest recognition that the Latin Women’s Symposium awards to the activist that fight to empower the community and who are an example of leadership for women.  The obstacles that Maru Mora Villalpando has faced in her life have not been a reason to give up but on the contrary, they motivate her to reach her goals with more determination.
        Join us next Saturday May 21st to award her with this recognition.</p> ',
'leerMas' => 'Read more',
'leerMenos' => 'Read less',
'grafico1' => 'Genesis Photography',
'newsReinventandonos' => '<h1>“Reinventándonos después de migrar”</br>
      Es el tema del Tercer Simposio de Mujeres Latinas</h1>
      <h2>Todas las familias que han llegado a los Estados Unidos han tenido que pasar por la situación de adaptar sus vidas a costumbres diferentes. Tomando en consideración que la temática de la migración está tan vinculada con la comunidad latina en Seattle, estado de Washington, el Tercer Simposio de Mujeres Latinas estará dedicado este año a abordar esta realidad.</h2>
      <h3>Amarilis Aranguren Sánchez <span class="grey"> / </span> April 04, 2016</h3>',
'newsReinventandonos1' => ' <p>“<span class="CapitalLetter">R</span>einventándonos después de migrar” es el tema alrededor del cual panelistas y conferencistas contarán a las 225 participantes del evento que sí es posible salir exitosas de esta transición. El proceso de adaptarse a una nueva cultura, a un nuevo ambiente, sin dejar de lado las costumbres que cada quien trae de su país y de sus familias, es el reto que la comunidad latina enfrenta día a día.</p>
        <p>De acuerdo a un informe de la Organización de Naciones Unidas, en los Estados Unidos viven 26 millones de inmigrantes latinoamericanos. Se trata de un gran grupo de personas que lucha día a día contra el racismo y la discriminación, esforzándose para tener una vida mejor.
        El proceso de instalarse en otro país sea por vías legales o no, genera en las familias una situación traumática que implica el distanciamiento físico de seres queridos y familiares. Las mujeres latinas tienen un rol importante en el proceso de adaptación de sus familias a un nuevo estilo de vida.</p>
        <p>El 21 de mayo de 2016, la activista por los derechos humanos de los latinos Maru Mora Villalpando contará cómo ha sido su experiencia en la defensa de la comunidad, su rol como fundadora de Latino Advocacy y mostrará como el liderazgo de las mujeres puede transformar realidades. </p>
       <p>Maru Mora Villalpando recibirá el reconocimiento “Puño de Oro” otorgado por el Simposio de Mujeres Latinas y estará a cargo de la conferencia principal del evento.</p>
       <p></p>
       <p>También participará como conferencista María-José “Cote” Soerens, directora ejecutiva de Puentes, una organización que moviliza recursos para ayudar psicológicamente a los latinos indocumentados en el estado deWashington. Así como Lizbeth Gutiérrez, candidata a Ph.D. en Washington State University y especialista en estudios sobre la mujer.</p>
       <p>La trabajadora social Elodia González mostrará con su ejemplo como el trabajo duro puede cambiar la vida de todos los que migran. Gonzáles ayuda a la comunidad latina desde Seamar y otras prácticas a mejorar sus problemas de ansiedad. Su historia mostrará la capacidad de transformación que tienen las mujeres, pues después de tener a sus hijos reinventó su carrera profesional hasta convertirse en un aporte invaluable a la comunidad.</p>
       <p>El Tercer Simposio de Mujeres Latinas quiere impulsar a todas las mujeres que migraron a este país e inspirarlas a lograr cada día más, pues la vida no termina al llegar a Estados Unidos. Ese es el principio de algo mejor. “Reinventándonos después de migrar” será una muestra de lo que es capaz la mujer latina con su tenacidad.</p>
       <p>La invitación es a participar en el Tercer Simposio de Mujeres Latinas que se realizará en las instalaciones del North Seattle College, el próximo sábado 21 de mayo de 2016. 225 mujeres tendrán la oportunidad de participar en este evento gratuito que se llevará a cabo dentro las 10:00 am y 3:30 pm. </p>'
 
];