<?php

return [
 'Quienes' =>'Quiénes Somos',
   'nomTania' => 'Tania Hino',
   'comiteTania' => 'Comité de Finanzas y Presentadora',
   'Tania' => '<p>Mi meta como organizadora del Simposio de Mujeres Latinas en el Colegio de North Seattle es crear unidad                entre este              grupo tan importante de la comunidad latina.
               Los sueños se cumplen y son posibles con trabajo arduo, así como el apoyo de las personas que tienes a tu alrededor. Empoderar a las mujeres latinas y fortalecer su capacidad de liderazgo es fundamental para generar un cambio en nuestra sociedad.</p>
             <p>Cada uno tenemos nuestros propios sueños en la vida, yo creo firmemente que las  latinas pueden lograr                  sus metas               cuando se lo  proponen. Mi sueño ha venido realizándose a través de un trabajo arduo y constante,  con la ayuda y el estímulo de  mucha                gente a mi   alrededor, incluyendo  miembros de mi familia, amigos, y   buenos  profesores que creyeron en mí.</p>  
               <p>Soy Licenciada en Trabajo Social con una maestría de la Universidad de Washington. También soy terapeuta  Adleriana (Teoría Adleriana de Alfred Adler) e instructora de  Educación para Padres en el Colegio del Norte de Seattle.
               Este simposio para la Mujer Latina era solo un sueño mío, pero ha sido posible gracias al gran apoyo del Programa de Educación para Padres del Colegio del Norte de Seattle.  Así como a todas las mujeres cuyas vidas hemos tocado de alguna manera desde el primer Simposio que realizamos hace 3 años, ahora somos un grupo de mujeres fuertes ayudando a nuestra comunidad.</p>
               <p>Como madre de tres niños mi sueño es que todos nuestros hijos crezcan y que puedan navegar lo mejor posible en el mundo, y así aumentar la cantidad de Mujeres Latinas como grandes ejemplos para toda la comunidad.  Necesitamos más Latinas superándose para demostrar a todos que uno si puede alcanzar sus sueños.</p>
               <p>Mi historia.</p>
               <p>Hace más de 20 años mi familia llegó a los Estados Unidos desde México en busca de una mejor calidad de vida. A los 15 años todavía yo no podía entender ni hablar bien el idioma inglés. La consejera académica de mi escuela secundaria me preguntó si yo tenía alguna idea de quería hacer cuando fuera adulta. Sin vacilación contesté: “¡Una enfermera!”.</p>
               <p>La consejera me miró desconcertada y procedió a darme una prueba de vocación profesional. Traté de hacer lo mejor posible con lo poco que entendía. La consejera calificó mi prueba y volvió con noticias sorprendentes para mí en ese momento, yo no sería más que una trabajadora común y corriente en un restaurante. Mi corazón se hundió por un tiempo pero mis esperanzas me aguantaron.</p> 
               <p>Desde ese día tomé la decisión de que, no sólo iba a sobresalir en la carrera que eligiera, sino que también sería un puente para animar y motivar a otros para que ellos también alcancen sus sueños, especialmente a la mujer latina.</p>',
 'nomJessica' => 'Jessica Cabrera',
 'comiteJessica' => 'Comité de Canastas y Registro',
  'Jessica'=>'<p>Quiero que sepan que como mujer Latina me llena de emoción, alegría y orgullo apoyar esta iniciativa y                                           participar por segunda vez como parte del comité de planificación en el tercer simposio de mujeres latinas.</p>
              <p>Este evento busca maximizar su potencial y resaltar la importancia de la mujer latina en la sociedad 
              estadounidense.</p>
            <p> Mi nombre es Jessica Cabrera, tengo 51 años, soy de nacionalidad peruana, feliz madre de dos maravillosas hijas de 33 y 21 años y   psicóloga    de profesión. Emigre a los Estados Unidos hace poco más de 11 años.    Convertida en madre soltera y con una niña pequeña de               10 diez años, me                 aleje de mi querida patria, familia,    hogar, idioma, tradiciones y costumbres y llegue a este país cargada de muchos               sueños, ilusiones y en busca            de  nuevas oportunidades y desafíos. </p>
             <p> Unos de los desafíos más grandes a los cuales me tuve que enfrentar fue sin duda alguna la barrera del idioma, aunado al comienzo de una nueva vida en un país desconocido y la crianza de una niña pequeña. Afortunadamente al cabo de unos años tuve la oportunidad de estudiar el idioma y con mucha constancia y perseverancia aún sigo enfrentándome a nuevos retos los cuales me inspiran a seguir trabajando por lograr mis objetivos personales y profesionales. Dentro de la parte personal encontré al compañero de mi vida, que me apoya constantemente y cree en mis ideales.</p>
             <p>Mientras mantenía un trabajo a tiempo completo y continuaba mis estudios en el college, siempre considere importante conocer de cerca cómo funciona el sistema educativo para que mi hija pudiera adaptarse rápidamente a la escuela y fue así como me fui involucrando poco a poco como voluntaria y fui participando como facilitadora y sirviendo como guía para muchos grupos de padres latinos, lo cual colaboró a la formación de lo que hoy en día se conoce como “Natural Leader” y llegue a convertirme en una de las primeras líderes naturales que tuvo el distrito escolar de Edmonds. </p>
             <p>Actualmente pertenezco al comité de EAACH que significa Alianza Equitativa para el éxito, tuve la oportunidad de completar el programa de certificación de Mentores para Padres (Parent Mentor) en el Edmonds Community College, obtuve una certificación como Educadora de Padres en Disciplina positiva, y trabajo con el grupo F.L.Y. (Foreign Language for Youth) como profesora de español para varias Escuelas Primarias de diferentes distritos. </p>
             <p> Esta vida es un constante aprendizaje y todas y cada una de nosotras podemos lograr nuestros objetivos y sueños siempre y cuando nos apoyemos y luchemos juntas como mujeres fuertes que somos, y esperamos que nuestras historias sirvan a la vez de inspiración para muchas mujeres que buscan un medio de apoyo para el beneficio de su desarrollo personal, como mujer, como esposa y como profesional. !Las esperamos con muchas ansias!</p>', 
  'leerMas' => 'Leer más',
'leerMenos' => 'Leer menos',
 'nomVelia' => 'Velia Lara',              
'comiteVelia' => 'Comité de Banquete-Decoración',
   'Velia' => '<p>Mi interés de ser parte del Comité Organizador es: que por medio de esta oportunidad pueda apoyar y facilitar los                             recursos necesarios para empoderar a otras mujeres. Creo firmemente en el papel tan importante que juega la mujer en la                            familia y en la sociedad. Nosotras como mujeres inmigrantes en este  país que pasamos por diferentes cambios y etapas                              necesitamos de ese apoyo que nos ayude a salir   
              adelante.</p>
   <p>En mi experiencia al llegar a vivir a este país fué una gran oportunidad de cambio, que también trajo                                          consigo muchas situaciones en las cuales he buscado reinventarme día a día para poder lograr mis objetivos y no desfallecer   en el                intento y luchar por lo quiero.</p>
               <p>Ya que yo soy de las mujeres que creen que no hay motivos para abandonar nuestros sueños y que es posible poder alcanzar lo que queremos y llevar también al mismo tiempo una vida equilibrada con los diferentes roles que nos tocan vivir.</p>
               <p>Soy originaria de Puebla, México. Estoy casada y soy madre de dos hermosos niños. Tengo casi 11 años viviendo aquí en el estado de Washington. Estudie Licenciatura en Turismo en mi país natal. Siempre he tenido el deseo de superarme continuamente y de aprender cosas nuevas cada día; ya que el saber te da poder. Por lo cual desde que llegue a este país ha sido un continuo aprendizaje y preparación. Quiero ser un modelo positivo y ejemplo vivo para mis hijos y enseñarles que si se puede a pesar de las barreras y obstáculos que te presente la vida.</p>
               <p>Actualmente trabajo en el Centro Familiar de Shoreline y de Northshore en la ciudad de Bothell como facilitadora del programa Aprender Jugando, el cual me ha dado la oportunidad de trabajar con familias de diferentes culturas. También obtuve una certificación como Educador de Padres en Disciplina Positiva y es algo que me encanta hacer, el compartir con otros padres nuevas técnicas para la crianza de nuestros hijos, que son nuestro gran futuro.</p>',
 'nomXimena' => 'Ximena Grollmus',   
 'comiteXimena' => 'Comité de Banquete',
  'Ximena' => '<p>Hola a todas las bellas mujeres, estoy muy feliz de estar colaborando en la organización de este simposio para mujeres   latinas  ya que  es un gran evento  necesario para crear conexiones y seguir fortaleciendo nuestra comunidad.
              Soy originaria de Concepción, Chile y vivo aquí en Seattle hace 18 años.  Lo que en un principio fue una aventura, solamente una  visita a mi prima, se transformó y desenvolvió poco a poco en lo que sería de mi vida por estos lados.  Estoy casada y tengo dos hijos maravillosos, de 13 y 10 años.</p>
             <p>En Chile, trabajé como profesora y posteriormente en Seattle estudié en el Departamento de Psicología Escolar de la Universidad de Washington,  Consejería Escolar.  Después de graduarme me tomé un tiempo para dedicarme a la crianza de mis hijos y pasar al menos sus primeros añitos con ellos.</p>
              <p>Luego me dediqué a trabajar haciendo consejería para niños.  Desarrollándome como madre  empezé a aprender del programa para padres de Disciplina Positiva y aprender más sobre Psicología Adleriana. Trabajé como consejera en un programa llamado FPS (Preservación de la Familia) con familias que han sido reportadas a los Servicios de protección a los menores (CPS).</p>
              <p>Estoy certificada por la "Positive Discipline Association" para enseñar el programa y para entrenar personas a enseñarlo.  He trabajado  con grupos de padres de diferentes culturas de distintos distritos escolares del  estado de Washington y diferentes grupos de profesores y personal de escuelas del área de Seattle y alrededores. El trabajo con padres y madres de familia es mi pasión y lo que me da mayor satisfacción personal es poder ver los cambios positivos que provoca en las familias.   Actualmente estoy de consejera escolar en una escuela primaria de Shoreline, y también lo disfruto mucho.</p>',
 'nomPerla' => 'Perla Mendoza',               
 'comitePerla' => 'Comité de Publicidad y Web',
   'Perla' => '<p>Retomar ese suspiro de esperanza y compartirlo con las demás mujeres que buscan                crecer en este país, es  lo que   me sigue motivando a ser parte de este simposio. Como           mujer, creo que tenemos el compromiso de  formar  a nuestras familias   con amor,                  respeto y educación.</p>           
             <p>Es importante reconocer nuestro roll, educarnos para así  poder motivar a  nuestras familias de que tenemos que evolucionar, enseñarles a soñar,  a crear metas y  sobre  todo apoyar a quien va a nuestro lado.</p>
              <p>Cuando uno migra sin importar bajo que circunstancia todos probamos ese sabor a vacío, ese sentir de dejar lo que se era, y aún en contra de nuestros ideales o perspectivas, la señora vida nos va moldeando. Crecemos consciente o inconscientemente, y ese cambio, esa evolución siempre será un regalo. </p>
              <p>Soy Perla, hija, madre, esposa, profesionista y migrante. Viajo con la vida, y a veces me pierdo en ella. Llegue al estado de Washington con dos maletas, las cuales las tuve que dejar y con ello algunas de mis limitaciones y miedos. Seguí mis sueños  y migre a Dublín.</p>
              <p>Después de experimentar ser madre y estudiante termine mi maestría en Aplicación de la Media Digial en Irlanda, la vida me regreso a Seattle. Hoy estoy aquí, ayudando en este evento para crecer junto con todas las mujeres que llegan al simposio con anhelos y sueños.</p>',
   'nomSixta' => 'Sixta Morel',                          
   'comiteSixta' => 'Comité de Publicidad',
   'Sixta' => '<p>Amo la gente y las historias detrás de sus caras, creo que las sonrisas, la buena energía y la bondad  pueden  hacer la diferencia             en nuestras vidas. Llegué al simposio como invitada el primer año del evento  cuando recién llegaba de la Republica Dominicana y                   disfruté tanto la experiencia que decidí unirme al comité organizador desde hace ya dos años.</p> 
            <p>Compartir con tantas mujeres luchadoras, inspiradoras, ha sido una experiencia que me llena de esperanza en cuanto  a el  futuro de las Latinas en los Estados Unidos. </p>
             <p>Vivo en Seattle junto a mi esposo e hijo, disfruto de las flores, la buena lectura y escribo periódicamente en mi   blog Gente, Historias y Sonrisas.</p>',
'nomAmarilis' => 'Amarilis Aranguren',
 'comiteAmarilis' => 'Comité de Contenido-Registro', 
 'Amarilis' => '<p>La injusticia es el motivo que siempre me ha llevado a levantar la voz para quejarme. En los Estados Unidos, los                               latinoamericanos son una minoría que aún está luchando por mostrar una cara más unida y así reclamar con fuerza más                                  igualdad. En el poco tiempo que tengo viviendo en Seattle, me he dado cuenta que las mujeres son súper trabajadoras y                                también se mantienen ocupadas del bienestar de su familia tanto en el ámbito privado como público. </p>
              <p>Cuando la mujer latina se sienta con fuerza para exigir igualdad, entonces garantizará una mejor vida para toda  su familia. Ayudar a todas las mujeres que han atravesado por una situación de adaptarse a una nueva vida, en un  nuevo país, con nuevas tradiciones es lo que me lleva a aportar a este proyecto. </p>
              <p>El Simposio de Mujeres Latinas me abrió las puertas a conocer una comunidad latina muy humana y comprometida con mejorar la vida de todas las personas que tienen a su alrededor. La solidaridad ayuda a tener comunidades más fuertes.</p>
              <p>Soy periodista, con maestría en Ciencias Políticas y Tecnologías Digitales Interactivas. Tengo más de 10 años de experiencia trabajando específicamente en producción de contenido para internet y marketing digital. También tengo un diplomado en Gerencia en Social Media del Centro Internacional de Actualización Profesional de la Universidad Católica Andrés Bello, en Venezuela.</p>
              <p>Fui responsable de la marca digital del canal de noticias Globovisión, en Venezuela, desde 2009 hasta 2014 y de las estrategias de posicionamiento en redes sociales que convirtieron a la televisora en el medio de comunicación venezolano con mejor presencia digital hasta 2013.</p>',           
'nomAngie' => 'Angélica Esquivel',              
'comiteAngie' => 'Comité de Voluntariado', 
      'Angie' => '<p>La frontera fue parte de mi vida desde niña, crecí en el norte de México, en la frontera con Estados 
              Unidos. En una comunidad bicultural divida por un río. Cruzar al “otro lado”, fue el pan de cada día. La cultura estadounidense y el idioma inglés formaron parte de mi crecimiento. El hablar inglés me ayudo al viajar a otros países y para relacionarme con personas de otras culturas.</p>
              <p>Por cuestiones del destino me mude a Alemania a estudiar y ahí, en un país totalmente diferente al mío, con un idioma desconocido, tuve que reinventarme para poder adaptarme a mi nueva realidad. No fue fácil, y al principio mayormente debido a la barrera del idioma, me sentí desvalida, ignorante y sobre todo fuera de lugar. Tuve que aprender las costumbres, tradiciones e ideología de mi nuevo hogar. Este proceso me hizo entender mejor a todas aquellas personas que como yo, dejan atrás su país, para realizar un sueño o mejorar su situación de vida.</p>
              <p>Soy administradora de profesión pero maestra por vocación. He estudiado en varias universidades en tres diferentes países, lo que me ha permitido tener una visión más general de los diferentes sistemas educativos. Me gusta la tecnología y siempre la he integrado tanto en mis clases como en las demás actividades que realizo. Creo que la mejor manera de que una persona puede superarse es a través del estudio. Me interesa ayudar a otros a que logren sus metas y tengan una mejor calidad de vida.</p>
              <p>Vivo en Seattle desde hace 4 años con mi marido y mis 2 hijos. Ahora en mi etapa de madre y ama de casa, una vez más he tenido que reinventarme. Me enfrento al reto extraordinario de criar a mis hijos en un hogar multilingüe y multicultural. Y al no trabajar formalmente, he buscado otras actividades donde puedo sentirme productiva y contribuir con la comunidad.</p>
              <p>Soy consultora en el área de ventas a Latinoamérica en el negocio familiar, trabajo de voluntaria en la biblioteca pública y soy parte de la mesa directiva de una cooperativa preescolar en español. Así mismo me siento muy afortunada de ser parte del simposio de mujeres latinas.</p>',
'nomVeronica' => 'Veronica Duran', 
 'comiteVeronica' => 'Comité de Recuerdos',
  'Veronica' => '<p>Vine del Ecuador hace 17 años, donde había estudiado Negocios Internacionales y sacado mi Maestría en Marketing.  Después de un  año de haber llegado a Portland, Oregón, se me presentó un trabajo en la Universidad de Salud y Ciencia de Oregón (OHSU) como Interprete de             Español.</p>
            <p>Este trabajo me dio la oportunidad de conocer a muchas personas de diferentes orígenes y culturas. A través de esta experiencia,   aprendí que las personas de habla hispana no solo buscaban ayuda con el idioma, sino que buscaban compartir parte de su vida con    alguien que tuviera algo en común.</p>
            <p>Ahora que me dedico a cuidar a mis tres hijos aquí en Seattle, me doy cuenta que yo también quiero compartir mis experiencias con otras mujeres para poder enriquecernos mutuamente y salir adelante.</p>',
 'nomleonor' => 'Leonor',   
'comiteLeonor' => 'Comité de Mesas de Información',
   'Leonor' =>'<p>Nací en Turbo un municipio costero del departamento de Antioquia en Colombia.
            Crecí en una familia de tres hermanas y un hermano. Mi madre ama de casa y mi padre vendedor ambulante de dulces y lotería. Estos dos seres humanos maravillosos especialmente mi madre, me inculcó que debía ser maestra porque era la profesión más prometedora de la época; ella no tuvo que esforzarse mucho porque desde niña jugaba a ser maestra y me encantaba, desde entonces esa fue mi meta.</p>
            <p>En 1996 termine mi bachiller en pedagogía y al año siguiente de mi graduación ya estaba trabajando con el departamento de Antioquia, trabaje entonces por 18 años en escuelas públicas de mi municipio, pero fue cuando estudié gerencia educativa, cuando mi vida profesional cambio por completo ya que pude tener el privilegio de compartir con maestros que cambiaron mi forma de ver la educación y desde ahí  quise cambiar un sistema educativo que me molestaba mucho, debido a que permitía la degradación de los jóvenes a los que estaba educando. Esto y motivos familiares permitieron que llegara a Estados Unidos con mis tres hijos muy consciente de que comenzaría desde cero.</p>
            <p>De esta manera viví lo que muchos hombres y mujeres pasamos aquí, esa sensación de soledad y desprotección, pero lo que más me dio y me sigue dando tristeza es ver cómo tú misma comunidad tú misma gente quiere cortarte las alas. Pero siempre he tenido en mi mente la convicción de que no permitiría que nadie quebrara mi espíritu.</p>
            <p>Así que seguí buscando oportunidades y me escribí en un curso de educación infantil donde conocí la persona que me relaciono en las dos escuelas en las que actualmente estoy trabajando a las cuales llamo bendiciones. Ya que me han dado la oportunidad de seguir aprendiendo, creciendo y conocer personas maravillosas.</p>
            <p>Desde el 2015 quise estar en el simposio después de ver la publicidad en los medios de comunicación, llame y se habían cerrado las inscripciones. Pero como el mundo es tan pequeño hoy estoy muy feliz de pertenecer al equipo organizador del mismo, con la convicción de que puedo aportar  un granito de arena y decirle a la mujer latina no permitas  que nadie quiebre tu  espíritu ¡sí podemos!</p>',    
'Aliados' => 'Nuestros Aliados',
'nomGuillermo' => 'Guillermo Carvajal',  
 'comiteGuillermo' => 'Comité de Finanzas',
 'Guillermo' =>'<p>Las mujeres son la clave para crear un mundo más justo y contenido, ellas tienen la capacidad y   experiencia de comprender lo qué            necesitan los seres humanos para  disfrutar una vida más sana y alegre.    Mientras más éxitos acumulan las mujeres en sus vidas,  más               segura y sana se siente su familia. Para mí,  los hijos de estas mujeres tienen una mejor posibilidad para triunfar académicamente  y                cumplir sus   propios sueños. Está en mi interés ver más y más mujeres latinas teniendo éxito.</p>
              <p>El éxito de nuestros estudiantes está ligado directamente a sus madres.  Las mujeres que han   participado en el Simposio de                      Mujeres Latinas aprecian el poder de tener esperanzas y aspiraciones.   Nosotros quienes tenemos la capacidad de extender una mano                   para que más y más mujeres puedan tener éxito,  debemos hacerlo. </p>
                <p> Nací en Costa Rica y fui criado en Nueva York, la ciudad que es conocida por muchos como “la gran Manzana”.  Mi trabajo es brindarle apoyo a las familia de las escuelas públicas de Seattle y tengo una maestría en desarrollo humano.  Durante los últimos 15 años, he trabajado en la rama de servicio social y he dedicado una gran parte de mi vida como adulto a defender los derechos humanos de todos.  También tengo muchos años de voluntariado apoyando la cultura y artes latinas. También he tenido el privilegio de trabajar con muchas comunidades étnicas y minorías.  Trabajar en escuelas con una gran población de Latinos, me ha dado una apreciación más profunda de los retos de las familias con quien comparto, especialmente las madres.</p>
                <p> Mi madre y el barrio a donde crecí han sido mi inspiración.  Históricamente las mujeres han detrás de sus hombres, apoyando de muchas maneras a sus maridos mientras ellos desarrollan sus carreras profesionales.  Pero ahora la economía mundial ha obligado a la familia a reconsiderar el papel "pasivo" de la madre, ahora las madres no tienen opción de ser solo damas de casa. Ellas están obligadas a salir al mundo y competir por puestos de trabajo por el bien de sus familias. Este nuevo mundo demanda que la mujer tenga la oportunidad de no solo soñar con  tener una buena carrera, pero también tener recursos y  oportunidades para sobresalir.</p>
                <p>Mi madre vino a este país en sus 30 años y paso el resto de sus días trabajando limpiando casas o haciendo trabajo para diferentes factorías. Ella tenía un buen corazón y era inteligente, pero vivíamos en una zona muy pobre y peligrosa de la ciudad de Nueva York. Nunca pudo encontrar y obtener contactos o recursos para realizar su propios sueños. En las madres con las que trabajo reconozco un poco de mi propia mamá, tienen aspiraciones y luchas similares, así como situaciones de tristeza y melancolía; momentos de risa y la esperanza. Cuando me siento a conversar con ellas las escucho y también a mi madre.</p>
                <p>La mayoría de las personas con las que trabajo son mujeres, siempre trato de recordar la experiencia con mi madre al estar con ellas. Siempre me esfuerzo por no poner “peros” a sus sueños y si están listas para “volar”, ayudarlas a buscar recursos que les aseguren un exitoso vuelo. Una gran parte de mi trabajo día a día es alimentar sus sueños y esperanzas.</p>'
 
];



