<?php

return [
  'Jessica'=> '<p>Quiero que sepan que como mujer Latina me llena de emoción, alegría y orgullo apoyar esta iniciativa y               participar como parte del comité de planificación en el segundo simposio de mujeres latinas, el cual busca               maximizar su potencial y resaltar la importancia de la mujer latina en la sociedad estadounidense.</p>', 
   'Tania' => '</p>Mi meta como organizadora del Simposio de Mujeres Latinas en el Colegio de North Seattle es crear                   unidad entre este grupo tan importante de la comunidad latina.
               Los sueños se cumplen y son posibles con trabajo arduo, así como el apoyo de las personas que tienes a tu alrededor. Empoderar a las mujeres latinas y fortalecer su capacidad de liderazgo es fundamental para generar un cambio en nuestra sociedad.</p>',
   'Tania1'=> '<p>Cada uno tenemos nuestros propios sueños en la vida, yo creo firmemente que las  latinas pueden lograr              sus metas cuando se lo  proponen. Mi sueño ha venido realizándose a través de un trabajo arduo y constante,             la ayuda y el estímulo de  mucha gente a mi   alrededor, incluyendo  miembros de mi familia, amigos, y                  buenos  profesores que creyeron en mí.</p>  
               <p>Soy Licenciada en Trabajo Social con una maestría de la Universidad de Washington. También soy terapeuta  Adleriana (Teoría Adleriana de Alfred Adler) e instructora de  Educación para Padres en el Colegio del Norte de Seattle.
               Este simposio para la Mujer Latina era solo un sueño mío, pero ha sido posible gracias al gran apoyo del Programa de Educación para Padres del Colegio del Norte de Seattle.  Así como a todas las mujeres cuyas vidas hemos tocado de alguna manera desde el primer Simposio que realizamos hace 3 años, ahora somos un grupo de mujeres fuertes ayudando a nuestra comunidad.</p>
               <p>Como madre de tres niños mi sueño es que todos nuestros hijos crezcan y que puedan navegar lo mejor posible en el mundo, y así aumentar la cantidad de Mujeres Latinas como grandes ejemplos para toda la comunidad.  Necesitamos más Latinas superándose para demostrar a todos que uno si puede alcanzar sus sueños.</p>
               <p>Mi historia</p>
               <p>Hace más de 20 años mi familia llegó a los Estados Unidos desde México en busca de una mejor calidad de vida. A los 15 años todavía yo no podía entender ni hablar bien el idioma inglés. La consejera académica de mi escuela secundaria me preguntó si yo tenía alguna idea de quería hacer cuando fuera adulta. Sin vacilación contesté: “¡Una enfermera!”.</p>
               <p>La consejera me miró desconcertada y procedió a darme una prueba de vocación profesional. Traté de hacer lo mejor posible con lo poco que entendía. La consejera calificó mi prueba y volvió con noticias sorprendentes para mí en ese momento, yo no sería más que una trabajadora común y corriente en un restaurante. Mi corazón se hundió por un tiempo pero mis esperanzas me aguantaron.</p> 
               <p>Desde ese día tomé la decisión de que, no sólo iba a sobresalir en la carrera que eligiera, sino que también sería un puente para animar y motivar a otros para que ellos también alcancen sus sueños, especialmente a la mujer latina.</p>',
   'Sixta' => '<p>“Llegué al simposio como invitada el primer año del evento cuando recién llegaba de mi país, disfruté               tanto la experiencia que decidí  unirme al comité organizador desde hace ya dos años. Compartir con tantas              mujeres luchadoras, inspiradoras, ha sido una experiencia que me llena de esperanza en cuanto a el futuro de            las Latinas en los EU. Feliz de colaborar con tan hermosa iniciativa". </p>',
   'Sixta1'=> '<p>“Amo la gente y las historias detrás de sus caras, creo que las sonrisas, la buena energía y la bondad              pueden hacer la diferencia en nuestras vidas” . Profesional de la comunicación bilingüe quien se inició en              los medios de comunicación en su natal Republica Dominicana  a los 17 años.  Su experiencia incluye la                  conducción y producción de televisión, conducción de noticias, entrevistas, Editora de Artes y Espectáculos,            maestrías de ceremonias, comerciales, voice overs y actuación. Graduada de Administración de Empresas y                 Locución, cuenta con diplomado en Periodismo Cultural, así como en Comunicación Estratégica y Relaciones                Públicas de la Universidad de Washington. Periódicamente escribe en su blog "Gente, Historias y Sonrisas”.              </p>',   
    'Elia' => '<p>Me gusta complementar mi tiempo libre integrándome a organizaciones que beneficien a mi comunidad tanto             aquí  en Seattle como en  mi comunidad de origen.
               también me gusta la fotografía,  leer, salir a caminar, hacer  yoga, la música y el café con una buena amiga.</p>',
   'Elia1' => '<p>  Mi nombre es Elia Gómez, nací en Guadalajara, Jalisco e inicié mi aventura como migrante hace 19 años               apoyando a  mi esposo en su oferta laboral.
                A el día de hoy, dos de nuestros hijos ahora universitarios y el pequeño en quinto grado de primaria.</p>
                <p>Soy consciente de la importancia de mi función en el rol familiar y disfruto mucho tener la oportunidad de apoyar e impulsar tanto a mis hijos como a mi esposo. </p> ',
 'Guillermo' =>'<p>Las mujeres son la clave para crear un mundo más justo y contenido, ellas tienen la capacidad y                       experiencia de comprender lo qué necesitan los seres humanos para  disfrutar una vida más sana y alegre.                  Mientras más éxitos acumulan las mujeres en sus vidas,  más segura y sana se siente su familia. Para mí,                  los hijos de estas mujeres tienen una mejor posibilidad para triunfar académicamente  y cumplir sus                       propios sueños. Está en mi interés ver más y más mujeres latinas teniendo éxito.</p>',
 'Guillermo1'=>'<p>El éxito de nuestros estudiantes está ligado directamente a sus madres.  Las mujeres que han                           participado en el Simposio de Mujeres Latinas aprecian el poder de tener esperanzas y aspiraciones.                       Nosotros quienes tenemos la capacidad de extender una mano para que más y más mujeres puedan tener éxito,                 debemos hacerlo. </p>
                <p> Nací en Costa Rica y fui criado en Nueva York, la ciudad que es conocida por muchos como “la gran Manzana”.  Mi trabajo es brindarle apoyo a las familia de las escuelas públicas de Seattle y tengo una maestría en desarrollo humano.  Durante los últimos 15 años, he trabajado en la rama de servicio social y he dedicado una gran parte de mi vida como adulto a defender los derechos humanos de todos.  También tengo muchos años de voluntariado apoyando la cultura y artes latinas. También he tenido el privilegio de trabajar con muchas comunidades étnicas y minorías.  Trabajar en escuelas con una gran población de Latinos, me ha dado una apreciación más profunda de los retos de las familias con quien comparto, especialmente las madres.</p>
                <p> Mi madre y el barrio a donde crecí han sido mi inspiración.  Históricamente las mujeres han detrás de sus hombres, apoyando de muchas maneras a sus maridos mientras ellos desarrollan sus carreras profesionales.  Pero ahora la economía mundial ha obligado a la familia a reconsiderar el papel "pasivo" de la madre, ahora las madres no tienen opción de ser solo damas de casa. Ellas están obligadas a salir al mundo y competir por puestos de trabajo por el bien de sus familias. Este nuevo mundo demanda que la mujer tenga la oportunidad de no solo soñar con  tener una buena carrera, pero también tener recursos y  oportunidades para sobresalir.</p>
                <p>Mi madre vino a este país en sus 30 años y paso el resto de sus días trabajando limpiando casas o haciendo trabajo para diferentes factorías. Ella tenía un buen corazón y era inteligente, pero vivíamos en una zona muy pobre y peligrosa de la ciudad de Nueva York. Nunca pudo encontrar y obtener contactos o recursos para realizar su propios sueños. En las madres con las que trabajo reconozco un poco de mi propia mamá, tienen aspiraciones y luchas similares, así como situaciones de tristeza y melancolía; momentos de risa y la esperanza. Cuando me siento a conversar con ellas las escucho y también a mi madre.</p>
                <p>La mayoría de las personas con las que trabajo son mujeres, siempre trato de recordar la experiencia con mi madre al estar con ellas. Siempre me esfuerzo por no poner “peros” a sus sueños y si están listas para “volar”, ayudarlas a buscar recursos que les aseguren un exitoso vuelo. Una gran parte de mi trabajo día a día es alimentar sus sueños y esperanzas.</p>'
 
      
];



