<?php

return [
    'Nuestra' => 'Nuestra Historia',
    'laHistoria' => ' <p>Tania Hino y Guillermo Carvajal se unieron hace 3 años para buscar formas de mejorar la calidad de vida de la comunidad latina, en especial sobre los retos de las mujeres y sus familias. Así surgió la idea de hacer el Simposio de Mujeres Latinas. Esta fue su manera de poner en práctica ideas y años de experiencia para ayudar a la comunidad.</p>  
        <p>Tania y Guillermo se conocieron en el Northgate Elementary cuando coincidieron como creadores de un programa para ayudar a más niños a cumplir sus sueños universitarios, llamado “De la cuna a la universidad”. Al tratar de enganchar a esta comunidad latina, surgió la necesidad de empezar a educar a los padres. Ellos son vitales para que sus niños no paren sus estudios al finalizar la preparatoria, se trata de una idea conjunta que debe convertirse en un proyecto familiar.
        Ir a la universidad debe ser el sueño de una familia, donde los padres son un pilar fundamental para que sus hijos alcancen el éxito académico. </p>
        <p>Con el trabajo ligado a las comunidades latinas en Seattle, tanto Tania como Guillermo se dieron cuenta de la gran responsabilidad que tienen las mujeres en asegurarle una mejor calidad de vida a los suyos. Considerando las situaciones que vivían estas personas, se unieron para empezar a empoderar e inspirar a otras mujeres a tener mejores vidas.</p>
        <p>Las madres son las que asumen el rol principal en la crianza de los sus hijos, por ende, son quienes inspiran a los miembros de la familia a fijar metas más altas en los ámbitos laborales y académicos. Con mujeres más fuertes y mejor autoestima todo es posible.</p>
        <p>Entre Tania y Guillermo llegaron a la conclusión de que comenzando con un Simposio de Mujeres Latinas podían inspirar a la comunidad a eliminar sus barreras migratorias y ver soluciones donde antes había problemas. La educación es la puerta principal para tener una mejor vida. Derrotar el miedo al sistema educativo era una de las metas principales.</p>
        <p>Tocar la vida de una mujer para darle herramientas de liderazgo es cambiar por completo la existencia de toda su familia, así como de la comunidad que les rodea. Una mujer con sueños y la voluntad para trabajar fuerte con el propósito de cumplir sus metas, es una energía imparable que arrastra consigo a quienes tiene cerca. </p>
        <p>El Simposio de Mujeres Latinas comenzó como un evento totalmente gratuito con 89 participantes en su primera edición, en su segunda edición acudieron 122 participantes y ahora en la tercera cita se espera una participación de 255 mujeres. </p>
        <p>Gracias al interés que ha despertado este evento en la comunidad de mujeres latinas durante los dos simposios anteriores, Tania y Guillermo han logrado sumar a más mujeres a este proyecto. El primer año del Simposio fue tan exitoso que varias mujeres con mucho talento y años de experiencia se acercaron a Tania, apoderándose la visión y el proyecto.  Guillermo sigue comprometido, apoyando y dando un a mano como aliado a esta iniciativa tan importante para nuestras mujeres.</p>
        <p>Algo tiene que cambiar. En vez de la mujer estar atrás de su pareja: ¿Por qué no unirse los dos y andar de mano a mano? Esto es una forma más saludable, enriquecedora y poderosa para hacer realidad los sueños de las mujeres y toda la familia. Darle herramientas y apoyo a las participantes es una gran parte de la visión del Simposio de Mujeres latinas.</p>
        <p>Esperamos que más hombres, esposos y sus hijos participen también, pues las mujeres son el pilar que sostiene a las familias. Su éxito, es positivo e importante para todos.</p> 
        <p>Nuestro sueño es organizar y reunir Mujeres Latinas de diversos niveles educativos, estratos socioeconómicos y culturales para formar una comunidad de apoyo mutuo. De esa manera nos levantaremos todos juntos como comunidad hacia un mundo mejor.</p>'
];

